name: Docker Image CI
on: pull_request_target
jobs:
  autoclose:
    runs-on: ubuntu-latest
    if: github.repository == 'RayWangQvQ/BiliBiliTool.Docs'
    steps:
    - uses: roots/issue-closer@v1.1
      with:
# 自动关闭不规范PR

name: Autocloser
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-close-message: "This PR was automatically closed because it did not follow the PR template."
        pr-pattern: ".*请问您是否明白：【yes】 -->.*"
